{{- if .Values.api.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kincare.fullname" . }}-api
  labels: {{- include "kincare.componentLabels" (dict "Chart" .Chart "Release" .Release "Values" .Values "component" "api") | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "kincare.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: api
  ports:
    - { name: http, port: {{ .Values.api.service.port }}, targetPort: http }
{{- if .Values.api.hl7Mllp.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kincare.fullname" . }}-mllp
  labels: {{- include "kincare.componentLabels" (dict "Chart" .Chart "Release" .Release "Values" .Values "component" "mllp") | nindent 4 }}
spec:
  type: {{ .Values.api.hl7Mllp.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "kincare.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: api
  ports:
    - { name: mllp, port: {{ .Values.api.hl7Mllp.port }}, targetPort: mllp, protocol: TCP }
{{- end }}
{{- if .Values.api.autoscaling.enabled }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "kincare.fullname" . }}-api
  labels: {{- include "kincare.componentLabels" (dict "Chart" .Chart "Release" .Release "Values" .Values "component" "api") | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "kincare.fullname" . }}-api
  minReplicas: {{ .Values.api.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.api.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.api.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}
{{- end }}
