import { Worker } from 'bullmq';
import type IORedis from 'ioredis';
import type { Logger } from 'pino';
import puppeteer from 'puppeteer';
import { S3Client, PutObjectCommand } from '@aws-sdk/client-s3';
import { sha256Hex } from '@kincare/shared';
import { prisma } from '@kincare/db';
import { jobDuration, jobsProcessed } from '../metrics';

interface Opts { connection: IORedis; prefix: string; logger: Logger; }

const s3 = new S3Client({
  endpoint: process.env.S3_ENDPOINT,
  region: process.env.S3_REGION ?? 'us-east-1',
  forcePathStyle: process.env.S3_FORCE_PATH_STYLE === 'true',
  credentials: process.env.S3_ACCESS_KEY ? {
    accessKeyId: process.env.S3_ACCESS_KEY,
    secretAccessKey: process.env.S3_SECRET_KEY ?? '',
  } : undefined,
});

function reportHtml(report: any): string {
  const rows = (report.testResults ?? []).map((t: any) => `
    <tr>
      <td>${t.testName}</td>
      <td>${t.resultValue} ${t.unit ?? ''}</td>
      <td>${t.referenceRange ?? ''}</td>
      <td>${t.flag ?? ''}</td>
    </tr>`).join('');
  return `<!doctype html><html><head><meta charset="utf-8"/>
    <title>Diagnostic Report ${report.id}</title>
    <style>
      body { font-family: -apple-system, Segoe UI, Roboto, sans-serif; padding: 32px; color: #111; }
      h1 { margin-bottom: 4px; } .muted { color: #666; }
      table { width: 100%; border-collapse: collapse; margin-top: 24px; }
      th, td { padding: 8px 12px; border-bottom: 1px solid #e5e7eb; text-align: left; }
      th { background: #f3f4f6; }
      .footer { margin-top: 48px; font-size: 12px; color: #6b7280; }
    </style></head><body>
    <h1>${report.display}</h1>
    <div class="muted">Code: ${report.code} • Issued: ${new Date(report.issuedAt).toISOString()}</div>
    <h3>Patient</h3>
    <div>${report.patient.user.firstName} ${report.patient.user.lastName} • MRN ${report.patient.mrn}</div>
    <h3>Conclusion</h3>
    <div>${report.conclusion ?? '—'}</div>
    <h3>Results</h3>
    <table><thead><tr><th>Test</th><th>Result</th><th>Reference</th><th>Flag</th></tr></thead>
      <tbody>${rows}</tbody></table>
    <div class="footer">Generated by Kincare • ${new Date().toISOString()}</div>
  </body></html>`;
}

export function startPdfWorker({ connection, prefix, logger }: Opts) {
  const worker = new Worker(
    'pdf',
    async (job) => {
      const { reportId } = job.data as { reportId: string };
      const report = await prisma.diagnosticReport.findUniqueOrThrow({
        where: { id: reportId },
        include: { testResults: true, patient: { include: { user: true } } },
      });

      const browser = await puppeteer.launch({
        headless: true, args: ['--no-sandbox', '--disable-setuid-sandbox'],
      });
      try {
        const page = await browser.newPage();
        await page.setContent(reportHtml(report), { waitUntil: 'networkidle0' });
        const pdf = await page.pdf({ format: 'A4', printBackground: true });

        const bucket = process.env.S3_BUCKET_REPORTS!;
        const key = `reports/${report.id}/${Date.now()}.pdf`;
        await s3.send(new PutObjectCommand({
          Bucket: bucket, Key: key, Body: pdf, ContentType: 'application/pdf',
          ServerSideEncryption: 'AES256',
        }));

        await prisma.reportAttachment.create({
          data: {
            reportId: report.id,
            fileName: `report-${report.id}.pdf`,
            contentType: 'application/pdf',
            bytes: pdf.length,
            s3Bucket: bucket, s3Key: key,
            sha256: sha256Hex(Buffer.from(pdf)),
          },
        });
        logger.info({ reportId, key }, 'PDF generated');
      } finally {
        await browser.close();
      }
    },
    { connection, prefix, concurrency: 2 },
  );

  worker.on('failed', (j, err) => {
    jobsProcessed.labels('pdf', 'failed').inc();
    logger.error({ jobId: j?.id, err: err.message }, 'pdf job failed');
  });
  worker.on('completed', (j) => {
    jobsProcessed.labels('pdf', 'completed').inc();
    if (j.processedOn && j.finishedOn) {
      jobDuration.labels('pdf').observe((j.finishedOn - j.processedOn) / 1000);
    }
  });
}
